"""increase_access_token_length

Revision ID: 21a19f0675f9
Revises: 1f340754640a
Create Date: 2025-07-06 10:49:08.814496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21a19f0675f9"
down_revision: Union[str, None] = "1f340754640a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oauth_account",
        "access_token",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=4096),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "oauth_account",
        "access_token",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
