"""add 'ended' column to show table

Revision ID: 7508237d5bc2
Revises: 93fb07842385
Create Date: 2025-06-10 21:25:27.871064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7508237d5bc2"
down_revision: Union[str, None] = "93fb07842385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "show",
        sa.Column(
            "ended", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("show", "ended")
    # ### end Alembic commands ###
