"""add_indexer_column_to_indexerqueryresult

Revision ID: eb0bd3cc1852
Revises: 5299dfed220b
Create Date: 2025-10-28 21:39:24.480466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb0bd3cc1852"
down_revision: Union[str, None] = "5299dfed220b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer_query_result", sa.Column("indexer", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer_query_result", "indexer")
    # ### end Alembic commands ###
